[Deterministic]
nbCompartment = 3
TotalArea = 2.5 * 1e6

# Upper compartment
lhy_1 = 550
lhy_2 = 1600
lhy_3 = 900
ra_1 = 2.5 * 1e6 * 0.04
ra_2 = 2.5 * 1e6 * 0.13
ra_3 = 2.5 * 1e6 * 0.83

# Bottom compartment
kMC = 0
aMC = 1
C_loss = 1000000000000000
M_loss = 1000000000000000
#kMS = 0.00043
aMS = 1
kCS = 200000
aCS = 1


[Stochastic]
# Base compartment]
kMS_lb = 0.000043
kMS_ub = 0.0043


[.Hydrotope 1]
k_e_num_lb = 9
k_e_num_ub = 900
e_min_lb = 10
e_min_ub = 50
diff_e_lb = 5
diff_e_ub = 25
alpha_lb = 0.7
alpha_ub = 1.6
k_is_lb = 0.002
k_is_ub = 0.2
k_sec_lb = 0.0095
k_sec_ub = 0.95
e_sec_lb = 25
e_sec_ub = 70

[.Hydrotope 2]
k_e_num_lb = 8.5
k_e_num_ub = 850
e_min_lb = 40
e_min_ub = 80
diff_e_lb = 40
diff_e_ub = 80
alpha_lb = 0.5
alpha_ub = 1.3
k_is_lb = 0.00055
k_is_ub = 0.055
k_sec_lb = 0.0023
k_sec_ub = 0.23
e_sec_lb = 130
e_sec_ub = 220

[.Hydrotope 3]
k_e_num_lb = 7.7
k_e_num_ub = 770
e_min_lb = 75
e_min_ub = 120
diff_e_lb = 80
diff_e_ub = 135
alpha_lb = 0.2
alpha_ub = 0.71
k_is_lb = 0.00025
k_is_ub = 0.025
k_sec_lb = 0.0015
k_sec_ub = 0.15
e_sec_lb = 320
e_sec_ub = 450


[Morris]
trajectories = 10
levels = 4
